name: Create Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name'
        required: true
        type: string

permissions:
  contents: write


jobs:
  create-release:
    name: Build and publish release
    runs-on: ubuntu-latest
    steps:
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ inputs.tag_name }}',
              sha: context.sha
            })
      - name: Get the version
        id: get_version
        run: echo "ABCTL_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
           go-version: 'stable'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean

      #- name: Make Release
        #run: make clean release
      #- name: Check version
        #run: ./build/release/abctl-$ABCTL_VERSION-linux-amd64/abctl version
      #- uses: ncipollo/release-action@v1
        #with:
          #generateReleaseNotes: true
          #artifacts: "build/release/*.tar.gz,build/release/*.zip"

      - uses: actions/checkout@v4
        with:
          repository: abuchanan-airbyte/homebrew-tap
          ssh-key: ${{ secrets.ABCTL_HOMEBREW_KEY }}
      - name: Replace version
        run: |
          sed -i 's/ABCTL_VERSION = ".*"/ABCTL_VERSION = ${{ inputs.tag_name }}/' Formula/abctl.rb
      - name: Show diff
        run: git diff
      - name: Commit changes
        run: |
          git config user.email "robot@airbyte.io"
          git config user.name "abctl release action"
          git commit -a -m "Update abctl to $ABCTL_VERSION"
      - name: Push change
        run: git push
